-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AppProvider" ADD VALUE 'SLACK';
ALTER TYPE "AppProvider" ADD VALUE 'DISCORD';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_CALENDAR_EVENT_CREATED';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_CALENDAR_EVENT_UPDATED';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_CALENDAR_EVENT_DELETED';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_DRIVE_FILE_CREATED';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_DRIVE_FILE_UPDATED';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_DRIVE_FILE_DELETED';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_DRIVE_FOLDER_CREATED';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_CALENDAR_CREATE_EVENT';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_CALENDAR_UPDATE_EVENT';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_CALENDAR_DELETE_EVENT';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_CALENDAR_FIND_AVAILABLE_TIMES';
ALTER TYPE "NodeType" ADD VALUE 'GMAIL_SEND_EMAIL';
ALTER TYPE "NodeType" ADD VALUE 'GMAIL_REPLY_TO_EMAIL';
ALTER TYPE "NodeType" ADD VALUE 'GMAIL_SEARCH_EMAILS';
ALTER TYPE "NodeType" ADD VALUE 'GMAIL_ADD_LABEL';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_DRIVE_UPLOAD_FILE';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_DRIVE_DOWNLOAD_FILE';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_DRIVE_MOVE_FILE';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_DRIVE_DELETE_FILE';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_DRIVE_CREATE_FOLDER';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_FORM_READ_RESPONSES';
ALTER TYPE "NodeType" ADD VALUE 'GOOGLE_FORM_CREATE_RESPONSE';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_NEW_EMAIL';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_EMAIL_MOVED';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_EMAIL_DELETED';
ALTER TYPE "NodeType" ADD VALUE 'ONEDRIVE_FILE_CREATED';
ALTER TYPE "NodeType" ADD VALUE 'ONEDRIVE_FILE_UPDATED';
ALTER TYPE "NodeType" ADD VALUE 'ONEDRIVE_FILE_DELETED';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_CALENDAR_EVENT_CREATED';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_CALENDAR_EVENT_UPDATED';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_CALENDAR_EVENT_DELETED';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_SEND_EMAIL';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_REPLY_TO_EMAIL';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_MOVE_EMAIL';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_SEARCH_EMAILS';
ALTER TYPE "NodeType" ADD VALUE 'ONEDRIVE_UPLOAD_FILE';
ALTER TYPE "NodeType" ADD VALUE 'ONEDRIVE_DOWNLOAD_FILE';
ALTER TYPE "NodeType" ADD VALUE 'ONEDRIVE_MOVE_FILE';
ALTER TYPE "NodeType" ADD VALUE 'ONEDRIVE_DELETE_FILE';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_CALENDAR_CREATE_EVENT';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_CALENDAR_UPDATE_EVENT';
ALTER TYPE "NodeType" ADD VALUE 'OUTLOOK_CALENDAR_DELETE_EVENT';
ALTER TYPE "NodeType" ADD VALUE 'SLACK_NEW_MESSAGE';
ALTER TYPE "NodeType" ADD VALUE 'SLACK_MESSAGE_REACTION';
ALTER TYPE "NodeType" ADD VALUE 'SLACK_CHANNEL_JOINED';
ALTER TYPE "NodeType" ADD VALUE 'DISCORD_NEW_MESSAGE';
ALTER TYPE "NodeType" ADD VALUE 'DISCORD_NEW_REACTION';
ALTER TYPE "NodeType" ADD VALUE 'DISCORD_USER_JOINED';
ALTER TYPE "NodeType" ADD VALUE 'TELEGRAM_NEW_MESSAGE';
ALTER TYPE "NodeType" ADD VALUE 'TELEGRAM_COMMAND_RECEIVED';
ALTER TYPE "NodeType" ADD VALUE 'SLACK_SEND_MESSAGE';
ALTER TYPE "NodeType" ADD VALUE 'SLACK_UPDATE_MESSAGE';
ALTER TYPE "NodeType" ADD VALUE 'SLACK_SEND_DM';
ALTER TYPE "NodeType" ADD VALUE 'SLACK_UPLOAD_FILE';
ALTER TYPE "NodeType" ADD VALUE 'DISCORD_SEND_MESSAGE';
ALTER TYPE "NodeType" ADD VALUE 'DISCORD_EDIT_MESSAGE';
ALTER TYPE "NodeType" ADD VALUE 'DISCORD_SEND_EMBED';
ALTER TYPE "NodeType" ADD VALUE 'DISCORD_SEND_DM';
ALTER TYPE "NodeType" ADD VALUE 'TELEGRAM_SEND_MESSAGE';
ALTER TYPE "NodeType" ADD VALUE 'TELEGRAM_SEND_PHOTO';
ALTER TYPE "NodeType" ADD VALUE 'TELEGRAM_SEND_DOCUMENT';
ALTER TYPE "NodeType" ADD VALUE 'FIND_CONTACTS';
ALTER TYPE "NodeType" ADD VALUE 'ADD_TAG_TO_CONTACT';
ALTER TYPE "NodeType" ADD VALUE 'REMOVE_TAG_FROM_CONTACT';
ALTER TYPE "NodeType" ADD VALUE 'DEAL_CREATED_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE 'DEAL_UPDATED_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE 'DEAL_DELETED_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE 'DEAL_STAGE_CHANGED_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE 'MOVE_DEAL_STAGE';
ALTER TYPE "NodeType" ADD VALUE 'ADD_DEAL_NOTE';
ALTER TYPE "NodeType" ADD VALUE 'APPOINTMENT_CREATED_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE 'APPOINTMENT_CANCELLED_TRIGGER';
ALTER TYPE "NodeType" ADD VALUE 'SCHEDULE_APPOINTMENT';
ALTER TYPE "NodeType" ADD VALUE 'UPDATE_APPOINTMENT';
ALTER TYPE "NodeType" ADD VALUE 'CANCEL_APPOINTMENT';
ALTER TYPE "NodeType" ADD VALUE 'STRIPE_PAYMENT_SUCCEEDED';
ALTER TYPE "NodeType" ADD VALUE 'STRIPE_PAYMENT_FAILED';
ALTER TYPE "NodeType" ADD VALUE 'STRIPE_SUBSCRIPTION_CREATED';
ALTER TYPE "NodeType" ADD VALUE 'STRIPE_SUBSCRIPTION_UPDATED';
ALTER TYPE "NodeType" ADD VALUE 'STRIPE_SUBSCRIPTION_CANCELLED';
ALTER TYPE "NodeType" ADD VALUE 'STRIPE_CREATE_CHECKOUT_SESSION';
ALTER TYPE "NodeType" ADD VALUE 'STRIPE_CREATE_INVOICE';
ALTER TYPE "NodeType" ADD VALUE 'STRIPE_SEND_INVOICE';
ALTER TYPE "NodeType" ADD VALUE 'STRIPE_REFUND_PAYMENT';
ALTER TYPE "NodeType" ADD VALUE 'GEMINI_GENERATE_TEXT';
ALTER TYPE "NodeType" ADD VALUE 'GEMINI_SUMMARISE';
ALTER TYPE "NodeType" ADD VALUE 'GEMINI_TRANSFORM';
ALTER TYPE "NodeType" ADD VALUE 'GEMINI_CLASSIFY';
ALTER TYPE "NodeType" ADD VALUE 'EXECUTE_WORKFLOW';
