import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { NuqsAdapter } from "nuqs/adapters/next/app";

import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { Provider } from "jotai";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { uploadRouter } from "@/app/api/uploadthing/core";
import { connection } from "next/server";
import { Suspense } from "react";
import { PostHogProvider, PostHogIdentifier } from "@/lib/posthog/client";
import { PageViewTracker } from "@/lib/posthog/page-view-tracker";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <NextSSRPlugin routerConfig={extractRouterConfig(uploadRouter)} />
        <PostHogProvider>
          <TRPCReactProvider>
            <Provider>
              <NuqsAdapter>
                <Suspense fallback={null}>
                  <PostHogIdentifier />
                  <PageViewTracker />
                </Suspense>
                {children}
                <Toaster closeButton={false} />
              </NuqsAdapter>
            </Provider>
          </TRPCReactProvider>
        </PostHogProvider>
      </body>
    </html>
  );
}
