import type {
  ReportCatalogItem,
  ReportField,
  ReportGroup,
  ReportGroupId,
} from "./types";

export const REPORT_GROUPS: readonly ReportGroup[] = [
  { id: "sales", label: "Sales", description: "Revenue, closeout, tax, gift card, contract, and product sales reports." },
  { id: "payment-processing", label: "Payment processing", description: "Card, ACH, autopay, settlement, expiry, and updater reports." },
  { id: "clients", label: "Clients", description: "Membership, retention, visit, marketing, balance, and account reports." },
  { id: "staff", label: "Staff", description: "Payroll, schedule, productivity, activity, task, and performance reports." },
  { id: "inventory", label: "Inventory", description: "Inventory levels, product sales, suppliers, stock changes, and age reports." },
] as const;

export const REPORT_CATEGORIES = {
  sales: ["All Sales Reports", "Administrative", "General Sales", "Sale Analysis", "Post-sale"],
  "payment-processing": ["All Payment Processing Reports", "Autopays", "CC & ACH Management"],
  clients: ["All Client Reports", "Visits & Retention", "Consumer Mode", "Marketing", "Client Accounts"],
  staff: ["All Staff Reports", "Productivity", "Payroll", "Administrative"],
  inventory: ["All Inventory Reports", "Management", "Sales"],
} satisfies Record<ReportGroupId, readonly string[]>;

export const REPORT_CATALOG: readonly ReportCatalogItem[] = [
  { id: "sales", groupId: "sales", name: "Sales", category: "General Sales", description: "View all your sales for a given date range." },
  { id: "daily-closeout", groupId: "sales", name: "Daily Closeout", category: "Administrative", description: "Find out how much cash should be in your cash register." },
  { id: "cash-drawer", groupId: "sales", name: "Cash Drawer", category: "Administrative", description: "Balance your cash drawer at the end of a shift or at the end of the day." },
  { id: "sales-by-service", groupId: "sales", name: "Sales by Service", category: "General Sales", description: "Pull sales data about each of the different services you offer." },
  { id: "sales-by-category", groupId: "sales", name: "Sales by Category", category: "General Sales", description: "Pull sales data about each revenue category at your business." },
  { id: "sales-by-product", groupId: "sales", name: "Sales by Product", category: "General Sales", description: "View all your product sales for a given date range." },
  { id: "gift-cards", groupId: "sales", name: "Gift Cards", category: "General Sales", description: "View a list of all your gift card sales and corresponding gift card numbers." },
  { id: "sales-by-supplier", groupId: "sales", name: "Sales by Supplier", category: "General Sales", description: "Pull sales data about each of your different product suppliers." },
  { id: "manage-online-orders", groupId: "sales", name: "Manage Online Orders", category: "Post-sale", description: "Check for new online product orders and update existing ones." },
  { id: "invoice", groupId: "sales", name: "Invoice", category: "Administrative", description: "View all your invoices for a given date range." },
  { id: "earned-revenue", groupId: "sales", name: "Earned Revenue", category: "Sale Analysis", description: "Find out how much revenue you've earned from services rendered and how much deferred revenue you have." },
  { id: "outstanding-series", groupId: "sales", name: "Outstanding Series", category: "Sale Analysis", description: "Find out how much deferred revenue you have in prepaid services that have yet to be rendered." },
  { id: "sales-promotions", groupId: "sales", name: "Promotions", category: "Post-sale", description: "See which clients used your promotion codes when making a purchase." },
  { id: "revenue-by-class", groupId: "sales", name: "Revenue by Class", category: "Sale Analysis", description: "Find out how much revenue each of your classes are generating." },
  { id: "average-revenue-analysis", groupId: "sales", name: "Average Revenue Analysis", category: "Sale Analysis", description: "Find out how much revenue each of my pricing options is generating." },
  { id: "returns", groupId: "sales", name: "Returns", category: "Post-sale", description: "Find out which services and products have been returned and why." },
  { id: "contract-sales", groupId: "sales", name: "Contract Sales", category: "General Sales", description: "Find out how much money in sales your contracts have brought in and which contracts are doing the best." },
  { id: "best-sellers", groupId: "sales", name: "Best Sellers", category: "Sale Analysis", description: "View your best selling products and services as well as their profit margins." },
  { id: "sales-tax", groupId: "sales", name: "Sales Tax", category: "Administrative", description: "Find how much sales tax you've collected." },
  { id: "voided-sales", groupId: "sales", name: "Voided Sales", category: "Administrative", description: "Generate a list of transactions that were voided as well as which staff member voided each." },
  { id: "gift-card-analysis", groupId: "sales", name: "Gift Card Analysis", category: "Sale Analysis", description: "Find out how successful you are at turning gift card recipients into long-term clients." },
  { id: "transactions", groupId: "payment-processing", name: "Transactions", category: "CC & ACH Management", description: "Find everything you need to know about credit transactions, including customer information, sale details, and transaction status." },
  { id: "approved-transactions", groupId: "payment-processing", name: "Approved Transactions", category: "CC & ACH Management", description: "View credit transactions that have been approved by the card-issuing bank but have not yet been batched." },
  { id: "autopay-detail", groupId: "payment-processing", name: "Autopay Detail", category: "Autopays", description: "Get detailed info about how much money you are going to make from upcoming autopays. You can also manually run or remove upcoming autopays." },
  { id: "settled-transactions", groupId: "payment-processing", name: "Settled Transactions", category: "CC & ACH Management", description: "View credit transactions that have been approved and batched. These are funds that you will be receiving in your bank account." },
  { id: "autopay-summary", groupId: "payment-processing", name: "Autopay Summary", category: "Autopays", description: "Get a snapshot of how much money you are going to make from upcoming autopays, and view how much you've made from autopays in the past." },
  { id: "pending-transactions", groupId: "payment-processing", name: "Pending Transactions", category: "CC & ACH Management", description: "View ACH transactions awaiting approval by the bank." },
  { id: "voided-rejected-transactions", groupId: "payment-processing", name: "Voided/Rejected Transactions", category: "CC & ACH Management", description: "View voided/rejected credit and ACH transactions. Also view open credit transactions that have an expired pre-authorization." },
  { id: "autopay-expirations", groupId: "payment-processing", name: "Autopay Expirations", category: "Autopays", description: "Find out which clients have autopay schedules that are expiring soon." },
  { id: "autopay-cc-expirations", groupId: "payment-processing", name: "Autopay CC Expirations", category: "Autopays", description: "Find out which clients have credit cards that will be expiring, thus preventing their future autopays from running." },
  { id: "card-updater", groupId: "payment-processing", name: "Card Updater", category: "CC & ACH Management", description: "View the number of cards updated in your system, the total amount of revenue protected, and what to expect for the next billing period." },
  { id: "membership", groupId: "clients", name: "Membership", category: "Client Accounts", description: "Find out how many members are at your business and what type of memberships they have." },
  { id: "mailing-lists", groupId: "clients", name: "Mailing Lists", category: "Marketing", description: "Pull important info about your clients, create mailing and emailing lists, and find out when your clients' birthdays are." },
  { id: "client-ratings-and-reviews", groupId: "clients", name: "Ratings and Reviews", category: "Consumer Mode", description: "View feedback about your business that was submitted through your client app." },
  { id: "account-balances", groupId: "clients", name: "Account Balances", category: "Client Accounts", description: "Find out which clients have positive and negative account balances at your business." },
  { id: "entry-logs", groupId: "clients", name: "Entry Logs", category: "Client Accounts", description: "Find out which clients and staff members have recently logged into your platform." },
  { id: "client-health-check", groupId: "clients", name: "Client Health Check", category: "Visits & Retention", description: "See client's health ratings that show how engaged your clients are." },
  { id: "client-cancellations", groupId: "clients", name: "Cancellations", category: "Visits & Retention", description: "Generate a list of all client cancellations as well as which staff member processed them. You can also undo a cancellation from this report." },
  { id: "first-visit", groupId: "clients", name: "First Visit", category: "Visits & Retention", description: "Find out when clients had their first visits, what services they took, and how many subsequent visits they've had since." },
  { id: "unpaid-visits", groupId: "clients", name: "Unpaid Visits", category: "Client Accounts", description: "Find out which clients owe you for visits that they did not pay for." },
  { id: "last-visit", groupId: "clients", name: "Last Visit", category: "Visits & Retention", description: "Find out when your clients' last visits were." },
  { id: "attendance-analysis", groupId: "clients", name: "Attendance Analysis", category: "Visits & Retention", description: "Find out which time of day has the highest attendance at your business." },
  { id: "pricing-option-expirations", groupId: "clients", name: "Pricing Option Expirations", category: "Client Accounts", description: "Find out which clients have series (prepaid services) that are expiring soon." },
  { id: "new-members", groupId: "clients", name: "New Members", category: "Client Accounts", description: "Pull a list of new members as well as what membership they purchased." },
  { id: "visits-remaining", groupId: "clients", name: "Visits Remaining", category: "Client Accounts", description: "View your clients' prepaid, unused visits, including if the visits have been booked or not." },
  { id: "attendance-without-revenue", groupId: "clients", name: "Attendance without Revenue", category: "Visits & Retention", description: "Tally the total amount on visits to your business for all service categories." },
  { id: "client-schedule-at-a-glance", groupId: "clients", name: "Schedule at a Glance", category: "Visits & Retention", description: "See what services your staff members are scheduled to render today." },
  { id: "retention", groupId: "clients", name: "Retention", category: "Visits & Retention", description: "Find out how effective your business is at retaining new and existing clients." },
  { id: "big-spenders", groupId: "clients", name: "Big Spenders", category: "Client Accounts", description: "Find out who is spending the most amount of money at your business." },
  { id: "client-indexes", groupId: "clients", name: "Client Indexes", category: "Client Accounts", description: "See customized categories of my clientele, at a glance." },
  { id: "referral-types", groupId: "clients", name: "Referral Types", category: "Marketing", description: "Find out how many referrals you've gotten per referral type." },
  { id: "no-return", groupId: "clients", name: "No Return", category: "Visits & Retention", description: "Find out which clients have not returned to your business after purchasing a service." },
  { id: "client-promotions", groupId: "clients", name: "Promotions", category: "Marketing", description: "See which clients used your promotion codes when making a purchase." },
  { id: "retention-management", groupId: "clients", name: "Retention Management", category: "Visits & Retention", description: "Export retention data to the 3rd party provider, Retention Management." },
  { id: "clients-per-teacher", groupId: "clients", name: "Clients per Teacher", category: "Visits & Retention", description: "See how many unique clients each of your staff members provided services to." },
  { id: "no-shows", groupId: "clients", name: "No-Shows", category: "Visits & Retention", description: "Find out which clients did not show up for their scheduled services." },
  { id: "client-arrivals", groupId: "clients", name: "Client Arrivals", category: "Visits & Retention", description: "Find out what time of day is most popular for clients arriving to use your facilities. Specifically for businesses using an Arrival service category." },
  { id: "online-metrics", groupId: "clients", name: "Online Metrics", category: "Consumer Mode", description: "Track what activities your clients are doing in your platform." },
  { id: "referrers", groupId: "clients", name: "Referrers", category: "Marketing", description: "Generate a list of clients who have referred other clients to your business." },
  { id: "event-payments", groupId: "clients", name: "Event Payments", category: "Client Accounts", description: "Find out which clients have an outstanding balance on a payment plan." },
  { id: "locker", groupId: "clients", name: "Locker", category: "Client Accounts", description: "Manage your clients' locker number assignments." },
  { id: "payroll", groupId: "staff", name: "Payroll", category: "Payroll", description: "Find out how much to pay your staff members for a given date range." },
  { id: "staff-schedule-at-a-glance", groupId: "staff", name: "Schedule at a Glance", category: "Administrative", description: "See what services your staff members are scheduled to render today." },
  { id: "time-clock", groupId: "staff", name: "Time Clock", category: "Payroll", description: "Find out how much to pay hourly employees for a given date range. You can also edit your employees' clocked-in hours from here." },
  { id: "staff-ratings-and-reviews", groupId: "staff", name: "Ratings and Reviews", category: "Productivity", description: "View feedback about your business that was submitted through your client app." },
  { id: "staff-cancellations", groupId: "staff", name: "Cancellations", category: "Administrative", description: "Generate a list of all client cancellations as well as which staff member processed them. You can also undo a cancellation from this report." },
  { id: "staff-schedule", groupId: "staff", name: "Staff Schedule", category: "Administrative", description: "Easily see all your staff members' schedules in one spot." },
  { id: "phone-book", groupId: "staff", name: "Phone Book", category: "Administrative", description: "Get a list of all staff members' phone numbers, emails, and mailing addresses." },
  { id: "staff-performance", groupId: "staff", name: "Staff Performance", category: "Productivity", description: "Get an overview of how efficient your staff members are compared to the amount of time they are scheduled." },
  { id: "staff-clients-per-teacher", groupId: "staff", name: "Clients per Teacher", category: "Productivity", description: "See how many unique clients each of your staff members provided services to." },
  { id: "appointment-metrics", groupId: "staff", name: "Appointment Metrics", category: "Productivity", description: "Find out how your appointment-based staff members are doing in terms of productivity and client retention." },
  { id: "pay-rates", groupId: "staff", name: "Pay Rates", category: "Payroll", description: "At a glance, see what your staff members' class pay rates are." },
  { id: "staff-activity", groupId: "staff", name: "Staff Activity", category: "Administrative", description: "Find out which staff members have accessed your platform and which screens they accessed while they were logged in." },
  { id: "staff-retail-sales-performance", groupId: "staff", name: "Retail Sales Performance", category: "Productivity", description: "Find out which staff members are best at upselling products during their appointment services." },
  { id: "tasks", groupId: "staff", name: "Tasks", category: "Administrative", description: "Generate a list of tasks that have been assigned to staff members, and view the status of each task." },
  { id: "assistants", groupId: "staff", name: "Assistants", category: "Payroll", description: "Find out how much to pay staff members who act as assistants." },
  { id: "trainer-conversions", groupId: "staff", name: "Trainer Conversions", category: "Productivity", description: "See which staff members successfully used a promotional appointment type to retain clients." },
  { id: "inventory-on-hand", groupId: "inventory", name: "Inventory on Hand", category: "Management", description: "Check and adjust your inventory levels." },
  { id: "inventory-sales-by-product", groupId: "inventory", name: "Sales by Product", category: "Sales", description: "View all your product sales for a given date range." },
  { id: "cost-of-goods-sold", groupId: "inventory", name: "Cost of Goods Sold", category: "Sales", description: "Find out which retail products are generating the most revenue for your business." },
  { id: "inventory-sales-by-supplier", groupId: "inventory", name: "Sales by Supplier", category: "Sales", description: "Pull sales data about each of your different product suppliers." },
  { id: "inventory-manage-online-orders", groupId: "inventory", name: "Manage Online Orders", category: "Sales", description: "Check for new online product orders and update existing ones." },
  { id: "inventory-change-log", groupId: "inventory", name: "Inventory Change Log", category: "Management", description: "View changes that have been made to your inventory levels." },
  { id: "inventory-retail-sales-performance", groupId: "inventory", name: "Retail Sales Performance", category: "Sales", description: "Find out which staff members are best at upselling products during their appointment services." },
  { id: "inventory-age", groupId: "inventory", name: "Inventory Age", category: "Management", description: "Identify your slowest moving products." },
] as const;

const f = {
  accountBalance: { id: "balance", name: "Balance", type: "Currency", description: "Current client account or payment balance." },
  amount: { id: "amount", name: "Amount", type: "Currency", description: "Transaction or payment amount." },
  arrivalTime: { id: "arrivalTime", name: "Arrival time", type: "Date", description: "Arrival or check-in timestamp." },
  averageRevenue: { id: "averageRevenue", name: "Average revenue", type: "Currency", description: "Average revenue per client, visit, or option." },
  booked: { id: "booked", name: "Booked", type: "Number", description: "Booked class or appointment count." },
  cardBrand: { id: "cardBrand", name: "Card brand", type: "Text", description: "Card brand or funding source." },
  category: { id: "category", name: "Category", type: "Text", description: "Revenue, product, client, or report category." },
  checkIns: { id: "checkIns", name: "Check-ins", type: "Number", description: "Checked-in visits." },
  className: { id: "className", name: "Class", type: "Text", description: "Class or appointment name." },
  client: { id: "client", name: "Client", type: "Text", description: "Client or member." },
  clientCount: { id: "clientCount", name: "Clients", type: "Number", description: "Unique clients represented." },
  contract: { id: "contract", name: "Contract", type: "Text", description: "Membership, contract, or pricing agreement." },
  cost: { id: "cost", name: "Cost", type: "Currency", description: "Product or fulfilment cost." },
  date: { id: "date", name: "Date", type: "Date", description: "Relevant report date." },
  deferredRevenue: { id: "deferredRevenue", name: "Deferred revenue", type: "Currency", description: "Revenue that has not yet been earned." },
  discount: { id: "discount", name: "Discount", type: "Currency", description: "Discount value." },
  email: { id: "email", name: "Email", type: "Text", description: "Email address." },
  endDate: { id: "endDate", name: "End date", type: "Date", description: "End, expiry, or cancellation date." },
  gross: { id: "gross", name: "Gross sales", type: "Currency", description: "Revenue before discounts, returns, and tax adjustments." },
  item: { id: "item", name: "Item", type: "Text", description: "Product, service, pricing option, or revenue item." },
  lastVisit: { id: "lastVisit", name: "Last visit", type: "Date", description: "Most recent visit date." },
  margin: { id: "margin", name: "Margin", type: "Percent", description: "Profit margin percentage." },
  method: { id: "method", name: "Payment method", type: "Text", description: "Card, ACH, cash, autopay, or payment source." },
  net: { id: "net", name: "Net sales", type: "Currency", description: "Final sales value after adjustments." },
  nextBillingDate: { id: "nextBillingDate", name: "Next billing", type: "Date", description: "Upcoming billing or renewal date." },
  orderStatus: { id: "orderStatus", name: "Order status", type: "Status", description: "Order fulfilment status." },
  pay: { id: "pay", name: "Pay", type: "Currency", description: "Payroll, rate, assistant pay, or commission amount." },
  phone: { id: "phone", name: "Phone", type: "Text", description: "Phone number." },
  product: { id: "product", name: "Product", type: "Text", description: "Retail product or SKU." },
  profit: { id: "profit", name: "Profit", type: "Currency", description: "Revenue minus cost." },
  promotion: { id: "promotion", name: "Promotion", type: "Text", description: "Promotion code or campaign." },
  quantity: { id: "quantity", name: "Quantity", type: "Number", description: "Quantity sold, used, remaining, or adjusted." },
  reason: { id: "reason", name: "Reason", type: "Text", description: "Reason or notes for the report row." },
  referrals: { id: "referrals", name: "Referrals", type: "Number", description: "Referral count." },
  renewalDate: { id: "renewalDate", name: "Renewal date", type: "Date", description: "Renewal date." },
  revenue: { id: "revenue", name: "Revenue", type: "Currency", description: "Revenue generated." },
  role: { id: "role", name: "Role", type: "Text", description: "Staff role." },
  scheduled: { id: "scheduled", name: "Scheduled", type: "Number", description: "Scheduled classes, appointments, or hours." },
  service: { id: "service", name: "Service", type: "Text", description: "Service or class type." },
  staff: { id: "staff", name: "Staff", type: "Text", description: "Staff member associated with the row." },
  startDate: { id: "startDate", name: "Start date", type: "Date", description: "Start date." },
  status: { id: "status", name: "Status", type: "Status", description: "Current status." },
  supplier: { id: "supplier", name: "Supplier", type: "Text", description: "Supplier or product category." },
  tax: { id: "tax", name: "Tax", type: "Currency", description: "Tax collected." },
  transactions: { id: "transactions", name: "Transactions", type: "Number", description: "Transaction count." },
  updatedAt: { id: "updatedAt", name: "Updated at", type: "Date", description: "Last update date." },
  used: { id: "used", name: "Used", type: "Number", description: "Used visits, redemptions, or credits." },
  visits: { id: "visits", name: "Visits", type: "Number", description: "Visit count." },
  worked: { id: "worked", name: "Worked", type: "Number", description: "Worked or rendered hours." },
} satisfies Record<string, ReportField>;

const salesLedgerFields = [f.date, f.item, f.client, f.method, f.status, f.gross, f.tax, f.net];
const salesAggregateFields = [f.category, f.transactions, f.quantity, f.gross, f.discount, f.tax, f.net];
const productSalesFields = [f.product, f.category, f.quantity, f.gross, f.discount, f.net, f.profit, f.margin];
const paymentFields = [f.date, f.client, f.method, f.status, f.amount];
const staffPerformanceFields = [f.staff, f.role, f.scheduled, f.worked, f.clientCount, f.revenue, f.pay];

export const REPORT_FIELDS_BY_ID = {
  "account-balances": [f.client, f.email, f.status, f.accountBalance, f.updatedAt],
  "approved-transactions": [f.date, f.client, f.method, f.cardBrand, f.amount, f.status],
  "appointment-metrics": [f.staff, f.scheduled, f.booked, f.checkIns, f.clientCount, f.revenue],
  "assistants": [f.staff, f.role, f.worked, f.pay, f.status],
  "attendance-analysis": [f.date, f.service, f.booked, f.checkIns, f.visits, f.status],
  "attendance-without-revenue": [f.date, f.service, f.clientCount, f.visits, f.revenue],
  "autopay-cc-expirations": [f.client, f.method, f.endDate, f.amount, f.status],
  "autopay-detail": [f.client, f.contract, f.nextBillingDate, f.amount, f.method, f.status],
  "autopay-expirations": [f.client, f.contract, f.endDate, f.nextBillingDate, f.amount, f.status],
  "autopay-summary": [f.contract, f.clientCount, f.transactions, f.revenue, f.deferredRevenue, f.status],
  "average-revenue-analysis": [f.contract, f.clientCount, f.transactions, f.revenue, f.averageRevenue],
  "best-sellers": [f.item, f.category, f.quantity, f.revenue, f.profit, f.margin],
  "big-spenders": [f.client, f.email, f.transactions, f.revenue, f.lastVisit, f.status],
  "card-updater": [f.date, f.client, f.cardBrand, f.amount, f.status],
  "cash-drawer": [f.date, f.method, f.gross, f.tax, f.net, f.status],
  "client-arrivals": [f.arrivalTime, f.client, f.service, f.staff, f.status],
  "client-cancellations": [f.client, f.contract, f.endDate, f.staff, f.reason, f.status],
  "client-health-check": [f.client, f.status, f.lastVisit, f.visits, f.revenue, f.staff],
  "client-indexes": [f.client, f.category, f.status, f.visits, f.revenue],
  "client-promotions": [f.promotion, f.client, f.date, f.discount, f.revenue, f.status],
  "client-ratings-and-reviews": [f.date, f.client, f.service, f.status, f.reason],
  "client-schedule-at-a-glance": [f.date, f.client, f.service, f.staff, f.status],
  "clients-per-teacher": [f.staff, f.clientCount, f.visits, f.revenue, f.status],
  "contract-sales": [f.contract, f.client, f.startDate, f.renewalDate, f.revenue, f.deferredRevenue, f.status],
  "cost-of-goods-sold": [f.product, f.category, f.quantity, f.cost, f.revenue, f.profit, f.margin],
  "daily-closeout": [f.date, f.transactions, f.gross, f.discount, f.tax, f.net],
  "earned-revenue": [f.date, f.service, f.clientCount, f.revenue, f.deferredRevenue, f.status],
  "entry-logs": [f.date, f.client, f.email, f.status, f.reason],
  "event-payments": [f.client, f.contract, f.amount, f.status, f.endDate],
  "first-visit": [f.client, f.date, f.service, f.staff, f.visits, f.status],
  "gift-card-analysis": [f.client, f.amount, f.revenue, f.used, f.accountBalance, f.status],
  "gift-cards": [f.date, f.client, f.amount, f.accountBalance, f.endDate, f.status],
  "inventory-age": [f.product, f.category, f.quantity, f.cost, f.updatedAt, f.status],
  "inventory-change-log": [f.updatedAt, f.product, f.quantity, f.reason, f.staff, f.status],
  "inventory-manage-online-orders": [f.date, f.product, f.quantity, f.amount, f.orderStatus],
  "inventory-on-hand": [f.product, f.supplier, f.quantity, f.cost, f.updatedAt, f.status],
  "inventory-retail-sales-performance": [f.staff, f.product, f.quantity, f.revenue, f.profit, f.margin],
  "inventory-sales-by-product": productSalesFields,
  "inventory-sales-by-supplier": [f.supplier, f.product, f.quantity, f.revenue, f.profit, f.margin],
  invoice: [f.date, f.client, f.item, f.amount, f.tax, f.status],
  "last-visit": [f.client, f.lastVisit, f.service, f.staff, f.visits, f.status],
  locker: [f.client, f.category, f.status, f.updatedAt],
  "mailing-lists": [f.client, f.email, f.phone, f.status, f.category],
  "manage-online-orders": [f.date, f.product, f.quantity, f.amount, f.orderStatus],
  membership: [f.client, f.contract, f.startDate, f.endDate, f.used, f.quantity, f.status],
  "new-members": [f.client, f.contract, f.startDate, f.amount, f.status],
  "no-return": [f.client, f.lastVisit, f.service, f.revenue, f.status],
  "no-shows": [f.date, f.client, f.service, f.staff, f.status],
  "online-metrics": [f.client, f.date, f.category, f.visits, f.status],
  "outstanding-series": [f.client, f.contract, f.quantity, f.used, f.deferredRevenue, f.endDate, f.status],
  "pay-rates": [f.staff, f.role, f.pay, f.status, f.updatedAt],
  payroll: [f.staff, f.role, f.worked, f.pay, f.status],
  "pending-transactions": paymentFields,
  "phone-book": [f.staff, f.role, f.email, f.phone, f.status],
  "pricing-option-expirations": [f.client, f.contract, f.endDate, f.quantity, f.used, f.status],
  "referral-types": [f.category, f.referrals, f.clientCount, f.revenue],
  referrers: [f.client, f.referrals, f.revenue, f.status],
  retention: [f.client, f.status, f.lastVisit, f.visits, f.revenue],
  "retention-management": [f.client, f.status, f.lastVisit, f.visits, f.reason],
  "returns": [f.date, f.client, f.item, f.quantity, f.amount, f.reason, f.status],
  "revenue-by-class": [f.className, f.staff, f.date, f.booked, f.revenue, f.averageRevenue],
  sales: salesLedgerFields,
  "sales-by-category": salesAggregateFields,
  "sales-by-product": productSalesFields,
  "sales-by-service": [f.service, f.category, f.transactions, f.gross, f.discount, f.tax, f.net],
  "sales-by-supplier": [f.supplier, f.product, f.quantity, f.gross, f.net, f.profit],
  "sales-promotions": [f.promotion, f.clientCount, f.transactions, f.discount, f.revenue],
  "sales-tax": [f.date, f.category, f.transactions, f.gross, f.tax, f.net],
  "settled-transactions": paymentFields,
  "staff-activity": [f.date, f.staff, f.role, f.status, f.reason],
  "staff-cancellations": [f.client, f.contract, f.endDate, f.staff, f.reason, f.status],
  "staff-clients-per-teacher": [f.staff, f.clientCount, f.visits, f.revenue, f.status],
  "staff-performance": staffPerformanceFields,
  "staff-ratings-and-reviews": [f.date, f.staff, f.service, f.status, f.reason],
  "staff-retail-sales-performance": [f.staff, f.product, f.quantity, f.revenue, f.profit, f.margin],
  "staff-schedule": [f.date, f.staff, f.service, f.scheduled, f.status],
  "staff-schedule-at-a-glance": [f.date, f.staff, f.service, f.scheduled, f.status],
  tasks: [f.date, f.staff, f.client, f.status, f.reason],
  "time-clock": [f.staff, f.date, f.scheduled, f.worked, f.pay, f.status],
  transactions: paymentFields,
  "trainer-conversions": [f.staff, f.clientCount, f.promotion, f.revenue, f.status],
  "unpaid-visits": [f.client, f.service, f.visits, f.accountBalance, f.status],
  "visits-remaining": [f.client, f.contract, f.quantity, f.used, f.endDate, f.status],
  "voided-rejected-transactions": paymentFields,
  "voided-sales": [f.date, f.client, f.item, f.amount, f.staff, f.status],
} satisfies Record<string, readonly ReportField[]>;
