/*
  Warnings:

  - The values [PARALLEL_BRANCH,MERGE,ERROR_HANDLER] on the enum `NodeType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "NodeType_new" AS ENUM ('INITIAL', 'MANUAL_TRIGGER', 'GOOGLE_FORM_TRIGGER', 'GOOGLE_CALENDAR_TRIGGER', 'GOOGLE_CALENDAR_EXECUTION', 'GMAIL_TRIGGER', 'GMAIL_EXECUTION', 'TELEGRAM_TRIGGER', 'TELEGRAM_EXECUTION', 'STRIPE_TRIGGER', 'HTTP_REQUEST', 'GEMINI', 'ANTHROPIC', 'OPENAI', 'DISCORD', 'SLACK', 'WAIT', 'CREATE_CONTACT', 'UPDATE_CONTACT', 'DELETE_CONTACT', 'CREATE_DEAL', 'UPDATE_DEAL', 'DELETE_DEAL', 'UPDATE_PIPELINE', 'CONTACT_CREATED_TRIGGER', 'CONTACT_UPDATED_TRIGGER', 'CONTACT_FIELD_CHANGED_TRIGGER', 'CONTACT_DELETED_TRIGGER', 'CONTACT_TYPE_CHANGED_TRIGGER', 'CONTACT_LIFECYCLE_STAGE_CHANGED_TRIGGER', 'IF_ELSE', 'SWITCH', 'LOOP', 'SET_VARIABLE', 'STOP_WORKFLOW');
ALTER TABLE "Node" ALTER COLUMN "type" TYPE "NodeType_new" USING ("type"::text::"NodeType_new");
ALTER TYPE "NodeType" RENAME TO "NodeType_old";
ALTER TYPE "NodeType_new" RENAME TO "NodeType";
DROP TYPE "public"."NodeType_old";
COMMIT;
